export const Cats = [
  {
    name: 'Kenneth',
    backgroundColor: '#c0a33f',
    color: '#000',
    srcName: 'creamBeigeCat',
    className: 'cat',
  },
  {
    name: 'Hilary',
    backgroundColor: '#937f7a',
    color: '#F9F4DA',
    srcName: 'blackCat',
    className: 'cat',
  },
  {
    name: 'Frida',
    backgroundColor: '#eca703',
    color: '#1E1E1E',
    srcName: 'hairlessCat',
    className: 'cat',
  },
  {
    name: 'Ethan',
    backgroundColor: '#bebe9f',
    color: '#1E1E1E',
    srcName: 'silverCat',
    className: 'cat',
  },
  {
    name: 'Dave',
    backgroundColor: '#595959',
    color: '#F9F4DA',
    srcName: 'yellowWhiteCat',
    className: 'cat',
  },
  {
    name: 'Ethel',
    backgroundColor: '#e3d9bf',
    color: '#F9F4DA',
    srcName: 'blueBlackCat',
    className: 'cat',
  },
  {
    name: 'Crispin',
    backgroundColor: '#af7a8f',
    color: '#1E1E1E',
    srcName: 'whiteCat',
    className: 'cat',
  },
  {
    name: 'Temperance',
    backgroundColor: '#f5cba7',
    color: '#F9F4DA',
    srcName: 'stripeyCat',
    className: 'cat',
  },
  {
    name: 'Vince the Impailer',
    backgroundColor: '#873714',
    color: '#F9F4DA',
    srcName: 'spider',
    className: 'spider',
  },
];
